"""refine dashboards and add sharing

Revision ID: 2995b4a799f7
Revises: c769aeaad506
Create Date: 2026-05-09 20:38:49.038159
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '2995b4a799f7'
down_revision: Union[str, None] = 'c769aeaad506'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboard_shares',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('dashboard_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('target_user_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('target_sector_id', sa.UUID(as_uuid=False), nullable=True),
    sa.Column('shared_by_user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['custom_dashboards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['target_sector_id'], ['sectors.id'], ),
    sa.ForeignKeyConstraint(['target_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dashboard_id', 'target_sector_id', name='uq_dash_share_sector'),
    sa.UniqueConstraint('dashboard_id', 'target_user_id', name='uq_dash_share_user')
    )
    op.create_index('idx_dashboard_shares_dashboard', 'dashboard_shares', ['dashboard_id'], unique=False)
    op.create_index('idx_dashboard_shares_sector', 'dashboard_shares', ['target_sector_id'], unique=False)
    op.create_index('idx_dashboard_shares_user', 'dashboard_shares', ['target_user_id'], unique=False)
    op.create_table('user_dashboard_settings',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('dashboard_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['custom_dashboards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'dashboard_id', name='uq_user_dash_settings')
    )
    op.create_index('idx_user_dash_settings_user', 'user_dashboard_settings', ['user_id'], unique=False)
    op.add_column('custom_dashboards', sa.Column('owner_user_id', sa.UUID(as_uuid=False), nullable=False))
    op.add_column('custom_dashboards', sa.Column('is_public', sa.Boolean(), nullable=False))
    op.drop_index(op.f('idx_custom_dashboards_user'), table_name='custom_dashboards')
    op.create_index('idx_custom_dashboards_user', 'custom_dashboards', ['owner_user_id'], unique=False)
    op.drop_constraint(op.f('custom_dashboards_user_id_fkey'), 'custom_dashboards', type_='foreignkey')
    op.create_foreign_key(None, 'custom_dashboards', 'users', ['owner_user_id'], ['id'])
    op.drop_column('custom_dashboards', 'is_default')
    op.drop_column('custom_dashboards', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_dashboards', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('custom_dashboards', sa.Column('is_default', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'custom_dashboards', type_='foreignkey')
    op.create_foreign_key(op.f('custom_dashboards_user_id_fkey'), 'custom_dashboards', 'users', ['user_id'], ['id'])
    op.drop_index('idx_custom_dashboards_user', table_name='custom_dashboards')
    op.create_index(op.f('idx_custom_dashboards_user'), 'custom_dashboards', ['user_id'], unique=False)
    op.drop_column('custom_dashboards', 'is_public')
    op.drop_column('custom_dashboards', 'owner_user_id')
    op.drop_index('idx_user_dash_settings_user', table_name='user_dashboard_settings')
    op.drop_table('user_dashboard_settings')
    op.drop_index('idx_dashboard_shares_user', table_name='dashboard_shares')
    op.drop_index('idx_dashboard_shares_sector', table_name='dashboard_shares')
    op.drop_index('idx_dashboard_shares_dashboard', table_name='dashboard_shares')
    op.drop_table('dashboard_shares')
    # ### end Alembic commands ###
