"""add system settings

Revision ID: 2b65909b3b0c
Revises: 7e4e6d812a0e
Create Date: 2026-05-09 22:29:22.485571
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2b65909b3b0c'
down_revision: Union[str, None] = '7e4e6d812a0e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    system_settings = op.create_table('system_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    # ### end Alembic commands ###

    # Add initial settings
    op.bulk_insert(
        system_settings,
        [
            {
                "key": "autopilot_max_widgets",
                "value": 20,
                "description": "Maximum number of widgets the Auto-Pilot can automatically add to a dashboard."
            },
            {
                "key": "autopilot_max_ticket_watchers",
                "value": 5,
                "description": "Maximum number of recent tickets to watch for updates in Auto-Pilot mode."
            }
        ]
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system_settings')
    # ### end Alembic commands ###
