"""add custom dashboards and widgets

Revision ID: 6afed0db83ec
Revises: 0007_phase8_hardening_indexes
Create Date: 2026-05-09 19:52:02.588754
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '6afed0db83ec'
down_revision: Union[str, None] = '0007_phase8_hardening_indexes'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('custom_dashboards',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('user_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_custom_dashboards_user', 'custom_dashboards', ['user_id'], unique=False)
    op.create_table('dashboard_widgets',
    sa.Column('id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('dashboard_id', sa.UUID(as_uuid=False), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False),
    sa.Column('x', sa.Integer(), nullable=False),
    sa.Column('y', sa.Integer(), nullable=False),
    sa.Column('w', sa.Integer(), nullable=False),
    sa.Column('h', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['dashboard_id'], ['custom_dashboards.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('idx_audit_events_admin_recent'), table_name='audit_events')
    op.drop_index(op.f('idx_metadata_key_definitions_active'), table_name='metadata_key_definitions')
    op.drop_index(op.f('idx_notifications_user_unread_recent'), table_name='notifications')
    op.drop_index(op.f('idx_sector_memberships_active_sector_role_user'), table_name='sector_memberships', postgresql_where='(is_active = true)')
    op.drop_index(op.f('idx_sla_policies_match'), table_name='sla_policies')
    op.alter_column('ticket_attachments', 'comment_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_column('ticket_attachments', 'visibility')
    op.drop_index(op.f('idx_tickets_active_by_sector'), table_name='tickets', postgresql_where="(((status)::text = ANY ((ARRAY['pending'::character varying, 'assigned_to_sector'::character varying, 'in_progress'::character varying, 'waiting_for_user'::character varying, 'on_hold'::character varying, 'reopened'::character varying])::text[])) AND (is_deleted = false))")
    op.drop_index(op.f('idx_tickets_admin_sla_due_active'), table_name='tickets', postgresql_where="((is_deleted = false) AND ((status)::text = ANY ((ARRAY['pending'::character varying, 'assigned_to_sector'::character varying, 'in_progress'::character varying, 'reopened'::character varying])::text[])))")
    op.drop_index(op.f('idx_tickets_admin_status_updated'), table_name='tickets', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('idx_tickets_beneficiary_active'), table_name='tickets', postgresql_where='(is_deleted = false)')
    op.drop_index(op.f('idx_tickets_requester_email_trgm'), table_name='tickets', postgresql_ops={'requester_email': 'gin_trgm_ops'}, postgresql_using='gin', postgresql_where='(requester_email IS NOT NULL)')
    op.drop_index(op.f('idx_tickets_search_vector'), table_name='tickets', postgresql_using='gin')
    op.drop_index(op.f('idx_tickets_title_trgm'), table_name='tickets', postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin', postgresql_where='(title IS NOT NULL)')
    op.drop_index(op.f('idx_tickets_unassigned'), table_name='tickets', postgresql_where="((assignee_user_id IS NULL) AND ((status)::text = ANY ((ARRAY['pending'::character varying, 'assigned_to_sector'::character varying])::text[])))")
    op.drop_column('tickets', 'search_vector')
    op.drop_index(op.f('idx_users_email'), table_name='users')
    op.drop_index(op.f('idx_users_keycloak_subject'), table_name='users')
    op.drop_index(op.f('idx_users_username'), table_name='users')
    op.drop_constraint(op.f('users_keycloak_subject_key'), 'users', type_='unique')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_index(op.f('ix_users_keycloak_subject'), 'users', ['keycloak_subject'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_keycloak_subject'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_unique_constraint(op.f('users_keycloak_subject_key'), 'users', ['keycloak_subject'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_users_username'), 'users', ['username'], unique=False)
    op.create_index(op.f('idx_users_keycloak_subject'), 'users', ['keycloak_subject'], unique=True)
    op.create_index(op.f('idx_users_email'), 'users', ['email'], unique=False)
    op.add_column('tickets', sa.Column('search_vector', postgresql.TSVECTOR(), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_tickets_unassigned'), 'tickets', ['current_sector_id', sa.literal_column('created_at DESC')], unique=False, postgresql_where="((assignee_user_id IS NULL) AND ((status)::text = ANY ((ARRAY['pending'::character varying, 'assigned_to_sector'::character varying])::text[])))")
    op.create_index(op.f('idx_tickets_title_trgm'), 'tickets', ['title'], unique=False, postgresql_ops={'title': 'gin_trgm_ops'}, postgresql_using='gin', postgresql_where='(title IS NOT NULL)')
    op.create_index(op.f('idx_tickets_search_vector'), 'tickets', ['search_vector'], unique=False, postgresql_using='gin')
    op.create_index(op.f('idx_tickets_requester_email_trgm'), 'tickets', ['requester_email'], unique=False, postgresql_ops={'requester_email': 'gin_trgm_ops'}, postgresql_using='gin', postgresql_where='(requester_email IS NOT NULL)')
    op.create_index(op.f('idx_tickets_beneficiary_active'), 'tickets', ['beneficiary_id', sa.literal_column('created_at DESC')], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('idx_tickets_admin_status_updated'), 'tickets', ['status', sa.literal_column('updated_at DESC'), sa.literal_column('id DESC')], unique=False, postgresql_where='(is_deleted = false)')
    op.create_index(op.f('idx_tickets_admin_sla_due_active'), 'tickets', ['sla_status', 'sla_due_at', 'priority', 'id'], unique=False, postgresql_where="((is_deleted = false) AND ((status)::text = ANY ((ARRAY['pending'::character varying, 'assigned_to_sector'::character varying, 'in_progress'::character varying, 'reopened'::character varying])::text[])))")
    op.create_index(op.f('idx_tickets_active_by_sector'), 'tickets', ['current_sector_id', 'priority', sa.literal_column('created_at DESC')], unique=False, postgresql_where="(((status)::text = ANY ((ARRAY['pending'::character varying, 'assigned_to_sector'::character varying, 'in_progress'::character varying, 'waiting_for_user'::character varying, 'on_hold'::character varying, 'reopened'::character varying])::text[])) AND (is_deleted = false))")
    op.add_column('ticket_attachments', sa.Column('visibility', sa.VARCHAR(length=20), server_default=sa.text("'private'::character varying"), autoincrement=False, nullable=False))
    op.alter_column('ticket_attachments', 'comment_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_index(op.f('idx_sla_policies_match'), 'sla_policies', ['priority', 'category', 'beneficiary_type', 'is_active'], unique=False)
    op.create_index(op.f('idx_sector_memberships_active_sector_role_user'), 'sector_memberships', ['sector_id', 'membership_role', 'user_id'], unique=False, postgresql_where='(is_active = true)')
    op.create_index(op.f('idx_notifications_user_unread_recent'), 'notifications', ['user_id', 'is_read', sa.literal_column('created_at DESC')], unique=False)
    op.create_index(op.f('idx_metadata_key_definitions_active'), 'metadata_key_definitions', ['is_active', 'key'], unique=False)
    op.create_index(op.f('idx_audit_events_admin_recent'), 'audit_events', [sa.literal_column('created_at DESC'), 'action', 'entity_type'], unique=False)
    op.drop_table('dashboard_widgets')
    op.drop_index('idx_custom_dashboards_user', table_name='custom_dashboards')
    op.drop_table('custom_dashboards')
    # ### end Alembic commands ###
