"""add description to custom_dashboards

Revision ID: 7e4e6d812a0e
Revises: e9e0542e8b33
Create Date: 2026-05-09 22:04:20.136185
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '7e4e6d812a0e'
down_revision: Union[str, None] = 'e9e0542e8b33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('custom_dashboards', sa.Column('description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('custom_dashboards', 'description')
    # ### end Alembic commands ###
