"""restore search_vector column

Revision ID: 8b305d56a8ec
Revises: 6afed0db83ec
Create Date: 2026-05-09 20:12:34.950580
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8b305d56a8ec'
down_revision: Union[str, None] = '6afed0db83ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tickets', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    op.create_index('idx_tickets_search_vector', 'tickets', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tickets_search_vector', table_name='tickets', postgresql_using='gin')
    op.drop_column('tickets', 'search_vector')
    # ### end Alembic commands ###
